### ISSUE TITLE
Analysis Period time step not working

### ISSUE THREAD

**Issue by ParametricMonkey** [ladybug-tools/ladybug#172]
Hi

There appears to be an issue with the Analysis Period component in Dynamo. If the start and end hour are the same, the Time Step reverts to every hour regardless of the input.

![A](https://user-images.githubusercontent.com/10913639/66368531-55095100-e9e4-11e9-9d03-82e8e8f04458.PNG)

![B](https://user-images.githubusercontent.com/10913639/66368535-58044180-e9e4-11e9-8b64-49a94c8d5fe7.PNG)

Running on Dynamo 2.0.3 and Revit 2018. 

[Ladybug bug.zip](https://github.com/ladybug-tools/ladybug/files/3700778/Ladybug.bug.zip)

**Comment by chriswmackey** [comment]
@ParametricMonkey ,

Thank you for reporting but this behavior is intentional. The `start_hour` and `end_hour` on the analysis period are meant to take out a slice of hours across the date range. This is what allows you to only look at the hours between 9AM and 5 PM for every day of the year, for example. So, when you go from 2AM to 2AM, 2:15AM is outside of that slice and so it does not belong.

If you want to get all of the timesteps between 2AM and 3AM, you should be plugging in a 3 for the `end_hour`.

I also know that the reason why you are posting this is because you want support for Daylight Savings time in the `AnalysisPeriod` and I think that is the correct issue to open here on the github (instead of this one). I recommend opening it here as a feature request and we will get to it when we can. I imagine that we won't expose the capability to set daylight savings on the plugins but you will be able to set it in the API, just like what we do with the `leap_year` property: https://www.ladybug.tools/ladybug/docs/ladybug.analysisperiod.html#ladybug.analysisperiod.AnalysisPeriod.is_leap_year

**Comment by ParametricMonkey** [comment]
@chriswmackey 

Thanks for your response. Maybe I wasn't clear in my question as I think this is still an issue and it should be re-open (which I'm not sure I can do?). It does tie in with DST but in any case this is a separate issue and I wouldn't classify it as a feature request.

In principal I understand how the time step works and understand that if the Start Hour and End Hour are the same the time step is irrelevant BUT only if the start and end days are the same. If I want to run an analysis from 2am on 21 Dec to 2am on 22 Dec with a time step of 4, it will only give me hour results. I've fix it via a workaround (add an extra hour and then subtract the results after) but it is not ideal.

Does this makes sense? Is this how you intended it to behave?

**Comment by chriswmackey** [comment]
@ParametricMonkey ,

I can confirm that this is definitely how we intended the `AnalysisPeriod` to behave. I'll admit that I might still not understand exactly what you are looking to achieve beyond the fact that what you are requesting does not seem to be a job for the `AnalysisPeriod`.

If what you want is some code that will give you a list of all datetimes at a certain timestep between two datetimes, you'll want to stick to using the DateTime module.  Here's some sample code that you can put in a Dynamo node if that's what you need:

```
from ladybug.dt import DateTime

datetimes_for_analysis = []

start_dt = DateTime(12, 21, 2)
end_dt = DateTime(12, 22, 2)
mintues_per_step = 15

while start_dt < end_dt:
    datetimes_for_analysis .append(start_dt)
    start_dt = start_dt.add_minute(mintues_per_step)

print(datetimes_for_analysis )
```
