### ISSUE TITLE
Psychrometric Chart -  Units?

### ISSUE THREAD

**Issue by mdengusiak** [ladybug-tools/ladybug#23]
@chriswmackey 
I currently you display Chart as Operative temperature - Humidity Ration,
should not be there Dry Bulb Temperature?

![image](https://user-images.githubusercontent.com/14005893/27055070-1d893e40-4fbb-11e7-8817-14cacd622421.png)

**Comment by chriswmackey** [comment]
@mdengusiak ,

Sorry for the late reply.  You should post questions on the current (legacy) version of Ladybug to this github repo:
https://github.com/mostaphaRoudsari/ladybug

"Operative Temperature" just refers to the method used to generate the thermal comfort polygon.  If you plug in a value for MRT into the psych chart component, it will display as dry bulb temperature (instead of assuming that the MRT is the same as the air temperature, hence operative temperature).

-Chris
