### ISSUE TITLE
Realtime loading of files from scripts directory

### ISSUE THREAD

**Issue by devngc** [ladybug-tools/ladybug#41]
Hi @mostaphaRoudsari,
Every time I make a change to a .py that I use in a grasshopper component, I need to restart rhino for the updated file to load correctly. Is there a way around this? Not having to restart GH and Rhino everytime a change is made in the file would be great!

**Comment by saeranv** [comment]
@devngc 
One method that works is to use the grasshopper "Read File" component to synchronize a file in a defined file path to your ghPython component. That way every time you save your .py file, your grasshopper component will automatically update. This is how I usually code in grasshopper, although am curious how others deal with this.

Approximately halfway through this blog there's a detailed explanation of how to set up the Read File method: 

http://www.blurrypaths.com/post/84032300754/ghpython-and-eclipse-workflow-to-edit-and-debug

**Comment by mostaphaRoudsari** [comment]
Hi @devngc, I assume you're referring to loading it as part of a the ladybug module.

My first suggestion is not to use Grasshopper for testing unless you're working on the development for the plugin. For core development you don't need Grasshopper for testing. Just use the editor. It's faster, easier and helps you think outside the limitations of Grasshopper.

But when you have to do it in Grasshopper, you will face this issue since Grasshopper caches the libraries once loaded and you need to `reload` the module each time if you want to see the most recent changes.

When I have to develop inside the Grasshopper what I do is that I load the libraries from the GitHub repository and not the installation folder. I have a file that is called `import_libraries_from_github.gh` which is a single GHPython component with a single input paths. A panel with the list of path to GitHub repositories is connected to path and here is the code inside the component.

```python
import sys
sys.path = paths + sys.path

import butterfly
import butterfly_grasshopper
import ladybug
import honeybee

ladybug.isplus = True
honeybee.isplus = True
print butterfly.__file__
print butterfly_grasshopper.__file__
print ladybug.__file__
print honeybee.__file__
```
I open this file right after I open Grasshopper and before opening any other files. This will ensure that the libraries are imported from the development folder and not the installation folder.

Then whenever you make an update to your code you need to reload the module to see the effect of changes. In your case it will look like this.

```python
import ladybug
reload(ladybug.windrose)
from ladybug.windrose import WindRose

#  your code here
```
Finally, make sure to remove the reload once the code is stable as it can make strange behaviors if you're reloading the module from inside different components.

**Comment by devngc** [comment]
Thank you @mostaphaRoudsar for sharing this.
While I get what you're doing here. It didn't work at my end. The path to github directory gets added to the list of system path. But rhino still refers to the scripts directory in my case.
 I will keep looking. Thank you again!

**Comment by devngc** [comment]
To anyone reading this in future, please make sure that you add path to the **github repo**  to system path and not the path to the ladybug directory inside the repo. @mostaphaRoudsari 's suggestion worked.
Thanks a lot! This is a huge help!

**Comment by devngc** [comment]
@saeranv,
Thank you so much for sharing. Till now I have coded inside the ghPython component in Grasshopper while making all contributions to legacy plugins. What you suggested could be a huge help for me. Thanks a lot!
